<?php

$t['Accueil'] = "Accueil";
$t['Acces'] = "Accès";
$t['Accessoires'] = "Accessoires";
$t['Acier'] = "Acier";
$t['Actions'] = "Actions";
$t['Active'] = "Activé";
$t['AdresseFacturation'] = "Adresse de facturation";
$t['AdresseLivraison'] = "Adresse de livraison";
$t['AdresseIP'] = "Adresse IP";
$t['Affichage'] = "Affichage";
$t['Affichage:'] = "Affichage";
$t['Aide'] = "Aide";
$t['Ajouter'] = "Ajouter";
$t['AjouterImagePhotomail'] = "Ajouter une image via Photomail";
$t['AjouterPrixDegressif'] = "Ajouter un prix dégressif";
$t['AjouterRoleApi'] = "Ajouter un rôle API";
$t['AjouterUnAttribut'] = "Ajouter un attribut";
$t['AjouterUneCampagneEmailing'] = "Ajouter une campagne d'emailing";
$t['AjouterUneImage'] = "Ajouter une image";
$t['AjouterUneOption'] = "Ajouter une option";
$t['AjouterUneRegle'] = "Ajouter une règle";
$t['AjouterUnRole'] = "Ajouter un rôle";
$t['AjouterUnUtilisateur'] = "Ajouter un utilisateur";
$t['AjouterUnUtilisateurApi'] = "Ajouter un utilisateur API";
$t['Alu'] = "Aluminium";
$t['Annuler'] = "Annuler";
$t['ApartirBase'] = "A partir d'une base";
$t['ApartirVent'] = "A partir d'une force de vent";
$t['Apercu'] = "Aperçu";
$t['APIshop'] = "E-boutiques";
$t['Application'] = "Application";
$t['Applications'] = "Applications";
$t['Approved'] = "Approuvé";
$t['Annee'] = "Année";
$t['AttenteTelechargement'] = "Loading...";
$t['AttentionNonSauvergarde'] = "Attention : cet enregistrement n'a pas été sauvegardé.";
$t['AttentionSuppressionImage'] = "Attention : l'ajout et la suppression d'images prennent effet immédiatement.";
$t['Attributs'] = "Attributs";
$t['Au'] = "au";
$t['Auteur'] = "Auteur";
$t['AvantagesProduit'] = "Le + produit";
$t['BatchCreationSku'] = "Batch pour créer des SKU";
$t['BatchDB'] = "Batchs de données";
$t['BatchProduitsApplications'] = "Batch pour déterminer une application à un produit";
$t['BatchSkuAttributs'] = "Batch pour associer un attribut à un SKU";
$t['BasePoidsOk'] = "La base choisie convient pour cette utilisation avec son poids de %poids kg ";
$t['BasePoidsPrb'] = "La base choisie ne convient pas à l'utilisation recherchée. Il manque %poids kg.";
$t['RolesAPI'] = "Rôles API";
$t['UtilisateursAPI'] = "Utilisateurs API";
$t['Barre'] = "Barré";
$t['BaseCatalogue'] = "Sélectionnez une base du catalogue";
$t['BaseDeDonnees'] = "Base de Données";
$t['Bienvenue'] = "Bienvenue";
$t['BilletBlog'] = "Billet de blog";
$t['BilletdeBlog'] = "Billet de ce blog";
$t['BilletsduBlog'] = "Billets du blog";
$t['Blog'] = "Blog";
$t['Calculer'] = "Calculer";
$t['CalculApartirBase'] = "Calcul à partir d'une base d'Event Flags";
$t['CalculApartirVent'] = "Calcul à partir d'une force de vent";
$t['CalculPoidsEvent'] = "Calculer le poids de la base de votre Event Flags";
$t['CalculResistanceVent'] = "Calculer la résistance au vent d'un mât";
$t['Caracteristiques'] = "Caractéristiques";
$t['CategorieParent'] = "Catégorie parent";
$t['Categories'] = "Catégories";
$t['CeMois:'] = "Statistiques pour le mois en cours.";
$t['Champs'] = "Champs";
$t['ChampIntitule'] = "Champs intitulé";
$t['ChampValeur'] = "Champs valeur";
$t['Changer'] = "Changer";
$t['Charger'] = "Charger";
$t['ChoisissezProduit'] = "Choisissez un type de produit.";
$t['ChoisissezTypeContenu'] = "Choisissez un type de contenu.";
$t['Classement'] = "Classement";
$t['CochezApplications'] = "Cochez les applications correspondantes :";
$t['CochezAttributs'] = "Cochez les attributs correspondants :";
$t['CoefficientAltitude'] = "Coefficients d'altitude";
$t['CoefficientTraineeMat'] = "Coefficient de trainée du mât";
$t['Colisage'] = "Colisage";
$t['Commentaires'] = "Commentaires";
$t['CommentairesDeBlog'] = "Commentaires de blog";
$t['CommentairesDesBlogs'] = "Commentaires des blogs";
$t['CommentairesDesProduits'] = "Commentaires des produits";
$t['CommentairesDuBillet'] = "Commentaires du billet";
$t['CommentairesDuBlog'] = "Commentaires du blog";
$t['CommentairesDuProduit'] = "Commentaires du produit";
$t['Comparatif'] = "Comparatif";
$t['Comparer'] = "Comparer";
$t['Composants'] = "Composants";
$t['Composition'] = "Composition";
$t['Conditionnement'] = "Conditionnement";
$t['Confirmer'] = "Confirmer";
$t['ConfirmerSuppression'] = "Êtes-vous sûr de vouloir supprimer ?";
$t['Conique'] = "conique";
$t['ControlerElementsSuivants'] = "Contrôler un des éléments suivants :";
$t['CorrespondanceMagento'] = "Correspondance Magento";
$t['ConseilsEntretien'] = "Conseils d'entretien";
$t['Contenu'] = "Contenu";
$t['Contenus'] = "Contenus";
$t['Couleur'] = "Couleur";
$t['Couleurs'] = "Couleurs";
$t['Creer'] = "Créer";
$t['CreerBlog'] = "Créer un blog";
$t['CreerNouveauCatalogue'] = "Créer un nouveau catalogue";
$t['CreerNouveauCommentaireBlog'] = "Créer un nouveau commentaire pour le billet de blog";
$t['CreerNouveauCommentaireProduit'] = "Créer un nouveau commentaire pour le produit";
$t['CreerNouveauModeleFiche'] = "Créer un nouveau modèle de fiche technique";
$t['CreerNouveauModeleFicheMatiere'] = "Créer un nouveau modèle de fiche matière";
$t['CreerNouveauProduit'] = "Créer un nouveau produit";
$t['CreerNouveauSku'] = "Créer un nouveau SKU";
$t['CreerNouvelleApplication'] = "Créer une nouvelle application";
$t['CreerNouvelleApplication'] = "Créer une nouvelle application";
$t['CreerNouvelleGamme'] = "Créer une nouvelle gamme";
$t['CreerNouvelleMatiere'] = "Créer une nouvelle matière";
$t['CreerNouvelAttribut'] = "Créer un nouvel attribut";
$t['CreerUtilisateur'] = "Créer un nouvel utilisateur";
$t['CreerBillet'] = "Création d'un billet de blog";
$t['CreerThemeBlog'] = "Créer un thème de blog";
$t['Cylindrique'] = "Cylindrique";
$t['Dashboard'] = "Dashboard";
$t['Date'] = "Date";
$t['DateAffichage'] = "Date d'affichage";
$t['DateCreation'] = "Date de création";
$t['DateDebutVente'] = "Date de mise en vente";
$t['DateEnvoi'] = "Date d'envoi";
$t['DateFinVente'] = "Date de fin de vente";
$t['Declinaisons'] = "Déclinaisons";
$t['DemandesCatalogue'] = "demandes de catalogue";
$t['DemandesDevis'] = "demandes de devis";
$t['DemandesInfo'] = "demandes d'information";
$t['Desactive'] = "Désactivé";
$t['Dessiner'] = "Dessiner";
$t['Description'] = "Description";
$t['DescriptionCourte'] = "Description courte";
$t['DesignationCommerciale'] = "Désignation commerciale";
$t['Diametre'] = "Diamètre";
$t['DiametreBase'] = "Diamètre d'une base.";
$t['Diaporama'] = "Diaporama";
$t['Dimensions'] = "Dimensions";
$t['Disapproved'] = "Désapprouvé";
$t['Domaine'] = "Domaine";
$t['DonneesAjoutees'] = "Données ajoutées";
$t['DonneesExistent'] = "Ces données existent déjà.";
$t['DonneesUpdated'] = "Données mises à jour";
$t['DoublonsSKU'] = "Doublons SKU/Ultralog";
$t['DoublonsSkuUltralog'] = "Il existe %nbre% doublons de références ultralog.";
$t['DuoCouleurs'] = "Duo de couleurs";
$t['Dupliquer'] = "Dupliquer";
$t['EcoLabel'] = "Eco label";
$t['EditerApplication'] = "Éditer une application";
$t['EditerAttribut'] = "Éditer un attribut";
$t['EditerCampagneEmailing'] = "Editer une campagne d'emailing";
$t['EditerCatalogue'] = "Éditer un catalogue";
$t['EditerCategorie'] = "Éditer une catégorie";
$t['EditerCommande'] = "Éditer une commande";
$t['EditerBillet'] = "Édition d'un billet de blog";
$t['EditerBlog'] = "Éditer un blog";
$t['EditerRegles'] = "Éditer les règles";
$t['EditerMatiere'] = "Éditer une matière";
$t['EditerModeleFiche'] = "Éditer un modèle de fiche technique";
$t['EditerModeleFicheMatiere'] = "Éditer un modèle de fiche matiere";
$t['EditerProduit'] = "Éditer un produit";
$t['EditerSku'] = "Éditer un SKU";
$t['EditerGamme'] = "Éditer une gamme";
$t['EditerThemeBlog'] = "Éditer le thème de blog";
$t['EditerUtilisateur'] = "Éditer un utilisateur";
$t['EditionCommentaire'] = "Editer le commentaire";
$t['EffortMat'] = "Effort subit sur le mât";
$t['EffortPavillon'] = "Effort subit sur le pavillon";
$t['Email'] = "Email";
$t['Emails'] = "Emails";
$t['Emailings'] = "Emailings";
$t['Emphase'] = "Emphase";
$t['EnqueteSatisfactionClients'] = "Enquete satisfaction clients";
$t['EnterIdApplications'] = "Indiquez des id applications";
$t['EnterIdProduits'] = "Indiquez des id produits";
$t['Enregistrer'] = "Enregistrer";
$t['EnregistrementAjoute'] = "Enregistrement ajouté.";
$t['EnregistrementSauvegarde'] = "Enregistrement sauvegardé.";
$t['EnregistrementSupprime'] = "Enregistrement supprimé.";
$t['Entrer'] = "Entrer";
$t['EventFlags'] = "Event flags";
$t['Envoyer'] = "Envoyer";
$t['Evidence'] = "Evidence";
$t['ExportCSV'] = "Export CSV";
$t['Exports'] = "Exports";
$t['ExporterEmails'] = "Exporter les emails";
$t['ExporterEmailsCorrects'] = "Exporter les emails corrects";
$t['ExporterEmailsIncorrects'] = "Exporter les emails non valides";
$t['ExporterFichierCouleurs'] = "Exporter le fichier pour la couleur ";
$t['ExporterProduits'] = "Exporter des produits";
$t['ExportSelonCouleurs'] = "Exporter SKU selon noms de couleurs";
$t['ExportSelonRal'] = "Exporter SKU selon RAL";
$t['ExpressionsTraduire'] = "Expressions à traduire";
$t['FamillesMatieres'] = "Famille de matières";
$t['FamilleVente'] = "Famille de vente";
$t['Fermer'] = "Fermer";
$t['Fibre'] = "Fibre de verre";
$t['Fiche'] = "Fiche";
$t['FicheMatiere'] = "Fiche Matière";
$t['FichesMatieres'] = "Fiches Matières";
$t['FichePerso'] = "Fiche personalisée";
$t['FichePersoProduit'] = "Fiche personalisée du produit";
$t['FicheTechnique'] = "Fiche technique";
$t['FichesTechniques'] = "Fiches techniques";
$t['FicheTechniqueProduit'] = "Fiche technique du produit";
$t['FichierTelecharge'] = "Le fichier suivant a été téléchargé";
$t['Filiale'] = "Filiale";
$t['FilialeConcernee'] = "Filiale concernée";
$t['FiliereRecyclage'] = "Filière de recyclage";
$t['FiltreReset'] = "Réinitialiser le filtre";
$t['FiltreSearch'] = "Rechercher";
$t['FiltrerEmails'] = "Filtrer des emails";
$t['FormeEventFlags'] = "Forme d'event flags";
$t['HauteurMats'] = "Hauteur des mâts";
$t['HauteurMat'] = "Hauteur totale de votre mât";
$t['HypotheseCalculs'] = "Hypothèse de calcul";
$t['ImageEmailing'] = "Image de votre emailing";
$t['Images'] = "Images";
$t['ImpossibleAjoutPrixNul'] = "Impossible d'ajouter un prix dégressif car le prix de base est nul.";
$t['Imprimer'] = "Imprimer";
$t['Informations'] = "Informations";
$t['IntroAdmin'] = "Bienvenue sur l'admin Alticcio.";
$t['ItemsAjoutes'] = "items ont été enregistrés.";
$t['ItemsDoublons'] = "items en doublons";
$t['Gamme'] = "Gamme";
$t['GammeEssentiel'] = "Essentiel";
$t['GammeExpert'] = "Expert";
$t['GammePro'] = "Pro";
$t['GestionUtilisateurs'] = "Gérer les utilisateurs";
$t['GestionBDD'] = "Gérer la base de données";
$t['GestionBillets'] = "Gestion des billets de blog";
$t['GestionContenu'] = "Gestion du contenu";
$t['GraphiqueTauxOuverture'] = "Progression des taux d'ouverture";
$t['GraphiqueTauxReactivite'] = "Progression des taux de réactivité";
$t['GraphiqueTauxClics'] = "Progression des taux de clics";
$t['GroupesUsers'] = "Profils";
$t['Image'] = "Image";
$t['Key'] = "Clé";
$t['KPI'] = "Indicateur clé";
$t['Langue'] = "Langue";
$t['Largeur'] = "Largeur";
$t['LegendeCalculVent'] = "Pour information, les poids des bases ne comprennent pas les lestages supplémentaires, platine (5kg) ou lest à eau (12kg).
<br/>Les cases vertes désignent les vents pour lesquels la base est conseillée. Les cases rouges désignent les utilisations déconseillées.
Le poids indiqué dans les cases de couleur correspond au poids recommandé pour la base.";
$t['LesImages'] = "Les images";
$t['Libelle'] = "Libellé";
$t['Lien'] = "Lien";
$t['Liste'] = "Liste";
$t['ListeOfAccessoiresProduit'] = "Liste des accessoires du produit";
$t['ListeOfApplications'] = "Liste des applications";
$t['ListeOfAttributs'] = "Liste des attributs";
$t['ListeOfBlogs'] = "Liste des blogs";
$t['ListeOfCatalogues'] = "Liste des catalogues";
$t['ListeOfCommandes'] = "Liste des commandes";
$t['ListeOfComposantsProduit'] = "Liste des composants - pièces détachées du produit";
$t['ListeOfDeclinaisonsProduit'] = "Liste des déclinaisons du produit";
$t['ListeOfCommentaires'] = "Liste des commentaires";
$t['ListeOfGammes'] = "Liste des gammes";
$t['ListeOfMatieres'] = "Liste des matières";
$t['ListeOfModelesFiches'] = "Liste des modèles de fiches techniques";
$t['ListeOfModelesFichesMatieres'] = "Liste des modèles de fiches matières";
$t['ListeOfProduits'] = "Liste des produits";
$t['ListeOfProduitsCategories'] = "Liste des produits de cette catégorie";
$t['ListeOfProduitsComplementaires'] = "Liste des produits complémentaires";
$t['ListeOfProduitsSimilaires'] = "Liste des produits similaires";
$t['ListeOfRoles'] = "Liste des rôles d'API";
$t['ListeOfSku'] = "Liste des SKU";
$t['ListeOfTables'] = "Liste des tables";
$t['ListeProduitsConfigurables'] = "Liste des produits configurables";
$t['ListeProduitsPerso'] = "Liste des produits personnalisés";
$t['ListeProduitsStandard'] = "Liste des produits standards";
$t['ListeProduitsSurMesure'] = "Liste des produits sur-mesure";
$t['ListeUtilisateurs'] = "Liste des utilisateurs";
$t['ListeUtilisateursApi'] = "Liste des utilisateurs de l'API";
$t['Login'] = "Login";
$t['Longueur'] = "Longueur";
$t['Maintenance'] = "Maintenance";
$t['MarquesFournisseurs'] = "Marques fournisseurs";
$t['Mat'] = "Mât";
$t['MatConseille'] = "Conseilé";
$t['MatDeconseille'] = "Déconseilé";
$t['Matiere'] = "Matière";
$t['Matieres'] = "Matières";
$t['Messages'] = "Messages/Devis";
$t['MetaDescription'] = "Meta Description";
$t['MetaKeywords'] = "Meta Keywords";
$t['MetaTitle'] = "Meta Title";
$t['Methode'] = "Méthode";
$t['MettreJourRefSku'] = "Mettre à jour la référence du sku";
$t['MinimumCommande'] = "Minimum de commande";
$t['ModeEmploi'] = "Mode d'emploi";
$t['ModifierMonCompte'] = "Modifier mon compte";
$t['ModifierUtilisateur'] = "Modifier un utilisateur";
$t['Mois'] = "Mois";
$t['MoisAout'] = "Août";
$t['MoisAvril'] = "Avril";
$t['MoisDecembre'] = "Décembre";
$t['MoisFevrier'] = "Février";
$t['MoisJanvier'] = "Janvier";
$t['MoisJuillet'] = "Juillet";
$t['MoisJuin'] = "Juin";
$t['MoisMai'] = "Mai";
$t['MoisMars'] = "Mars";
$t['MoisNovembre'] = "Novembre";
$t['MoisOctobre'] = "Octobre";
$t['MoisSeptembre'] = "Septembre";
$t['MomentInertieMini'] = "Moment d'inertie mini";
$t['MomentPied'] = "Moment au pied";
$t['MonCompte'] = "Mon compte";
$t['Montages'] = "Montages";
$t['MoyenneClics'] = "Taux moyen de clics";
$t['MoyenneDesabonnements'] = "Moyenne désabonnements";
$t['MoyenneNPAI'] = "Taux moyen des NPAI";
$t['MoyenneOuverture'] = "Taux moyen d'ouverture";
$t['MoyenneReactivite'] = "Taux moyen de réactivité";
$t['NbreCataloguesMois'] = "Nombre de catalogues par mois";
$t['NbreContactsMois'] = "Nombre de contacts par mois";
$t['NbreDevisMois'] = "Nombre de devis par mois";
$t['NbreEmailDansDB'] = "Nombre d'emails dans votre fichier";
$t['NbreEmailDesabonnes'] = "Nombre de désabonnés suite à cet email";
$t['NbreEmailEnvoyes'] = "Nombre d'emails envoyés";
$t['NbreEmailOuvert'] = "Nombre d'emails ouverts (cumulés)";
$t['NbreEmailCliques'] = "Nombre d'emails cliqués (cumulés)";
$t['NbreReponses'] = "Nbre de réponses";
$t['NettoyerBase'] = "Nettoyage de la base de données";
$t['NettoyerDoublonsSku'] = "Nettoyer les doublons des SKU";
$t['NettoyerLaBase'] = "Nettoyer la base";
$t['Nom'] = "Nom";
$t['NomCampage'] = "Nom de la campagne";
$t['Norme'] = "Norme";
$t['NoteBasPageSatisfaction'] = "Résultats établis à partir des %nbA% réponses enregistrées pendant la semaine ( par rapport aux %nbB% réponses de la semaine précédente).";
$t['NoteGlobale'] = "Note globale";
$t['NoteGlobale2'] = "Note globale <br/>de la satisfaction des clients";
$t['Nouveau'] = "Nouveau";
$t['NouveauCatalogue'] = "Nouveau catalogue";
$t['NouveauCommentaire'] = "Nouveau commentaire";
$t['NouveauModeleFiche'] = "Nouveau modèle de fiche technique";
$t['NouveauProduit'] = "Nouveau produit";
$t['NouveauRole'] = "Nouveau rôle";
$t['NouveauSku'] = "Nouveau SKU";
$t['NouveauTheme'] = "Nouveau thème";
$t['NouvelAttribut'] = "Nouvel attribut";
$t['NouvelUtilisateur'] = "Nouvel utilisateur";
$t['NouvelleApplication'] = "Nouvelle application";
$t['NouvelleCategorie'] = "Nouvelle catégorie";
$t['NouvelleCommande'] = "Nouvelle commande";
$t['NouvelleGamme'] = "Nouvelle gamme";
$t['NouvelleMatiere'] = "Nouvelle matière";
$t['obligatoire'] = "obligatoire";
$t['Offline'] = "Off line";
$t['Offre'] = "Offre";
$t['Online'] = "On line";
$t['Option'] = "Option";
$t['Options'] = "Options";
$t['Ordre'] = "Ordre";
$t['OrganisationsInter'] = "Organisations internationales";
$t['Ou'] = "Ou";
$t['OubliPassword'] = "Mot de passe oublié ?";
$t['Outils'] = "Outils";
$t['Parametres'] = "Paramètres";
$t['ParametresUtilisateur'] = "Paramètres de l'utilisateur";
$t['Parent'] = "Parent";
$t['ParPage'] = "par page";
$t['PasAfficher'] = "Ne pas afficher";
$t['Password'] = "Password";
$t['Pavillon'] = "Pavillon";
$t['Pays'] = "Pays";
$t['Personnalisation'] = "Personnalisation";
$t['PictosVente'] = "Pictos vente";
$t['Poids'] = "Poids";
$t['PoidsNecessaire'] = "Poids nécessaire";
$t['PremiereLigneNomColonne'] = "La première ligne n'est pas comptabilisée, elle sert de nom de colonne";
$t['Presentation'] = "Présentation";
$t['Prix'] = "Prix";
$t['PrixDegressifs'] = "prix dégressifs";
$t['PrixFranco'] = "La grille de frais de port s'applique à ce prix.";
$t['PrixHT'] = "Prix HT";
$t['PrixUnitaire'] = "Prix unitaire";
$t['Produits'] = "Produits";
$t['ProduitsComplementaires'] = "Produits complémentaires";
$t['ProduitsOrphelins'] = "Produits orphelins";
$t['ProduitsSimilaires'] = "Produits similaires";
$t['Profondeur'] = "Profondeur";
$t['QrCode'] = "QrCode";
$t['QualiteAccueil'] = "Qualité <br/>de l'accueil";
$t['QualiteEmballage'] = "Qualité <br/>de l'emballage";
$t['QualiteLivraison'] = "Délais <br/>de livraison";
$t['QualitePose'] = "Pose & installation";
$t['QualitePrix'] = "Rapport <br/>qualité / prix";
$t['QualiteProduit'] = "Qualité <br/>du produit";
$t['QualiteReponse'] = "Qualité <br/>des réponses";
$t['Quantite'] = "Quantité";
$t['QuelquesOutils'] = "Quelques outils";
$t['QuestionAccueil'] = "Accueil";
$t['QuestionEmballage'] = "Emballage";
$t['QuestionLivraison'] = "Livraison";
$t['QuestionPose'] = "Pose";
$t['QuestionPrix'] = "Prix";
$t['QuestionProduit'] = "Produit";
$t['QuestionReponses'] = "Réponse";
$t['RechercheAvancee'] = "Recherche avancée";
$t['Reduction'] = "Réduction";
$t['ReductionPourcentage'] = "% de réduction";
$t['Reference'] = "Référence";
$t['Referencement'] = "Référencement";
$t['Referencement:'] = "Référencement";
$t['RefRAL'] = "Ref. RAL";
$t['RefUltralog'] = "Ref. Ultralog";
$t['Regions'] = "Régions";
$t['ReglesRole'] = "Règles pour le rôle";
$t['ReglesUtilisateur'] = "Règles pour l'utilisateur";
$t['Reinitialiser'] = "Réinitialiser";
$t['RepartitionEmailingsPays'] = "Répartition des emailings par pays";
$t['ReportingSatisfaction'] = "Reporting Satisfaction";
$t['Resultat'] = "Résultat";
$t['ResultatBaisse'] = "en baisse";
$t['ResultatEgal'] = "identique";
$t['ResultatHausse'] = "en progression";
$t['ResultatsSemaineAvant'] = "Résultats par rapport à la semaine précédente : ";
$t['Retour'] = "Retour";
$t['RetourCatalogue'] = "Retour au catalogue";
$t['RetourBlog'] = "Retour au blog";
$t['RetourListeStats'] = "Retour aux statistiques";
$t['Role'] = "Rôle";
$t['Roles'] = "Rôles";
$t['Satisfaction'] = "Satisfaction";
$t['Sauvegarder'] = "Sauvegarder";
$t['SchemaDB'] = "Schéma";
$t['SelectAnnee'] = "Sélectionnez une année : ";
$t['SelectFichier'] = "Sélectionnez votre fichier : ";
$t['SelectFiliale'] = "Sélectionnez une filiale : ";
$t['SelectLangue'] = "Sélectionnez une langue : ";
$t['Selectionnes'] = "Sélectionnés";
$t['SelectionnezBillet'] = "Sélectionnez un billet de blog";
$t['SelectionnezTable'] = "Sélectionnez une table dans la liste.";
$t['SemaineDu'] = "Semaine du ";
$t['SesDimensions'] = "Dimensions";
$t['SesDroits'] = "Ses droits";
$t['SesResultats'] = "Ses résultats";
$t['ShortUlr'] = "Short Urls";
$t['SkuOrphelins'] = "SKU orphelins";
$t['SkuSansFamille'] = "SKU sans famille de vente";
$t['SkuSansNom'] = "SKU sans nom";
$t['Spam'] = "Spam";
$t['SonIdentite'] = "Son identité";
$t['Souligne'] = "Souligné";
$t['Statistiques'] = "Statistiques";
$t['StatsApiBoutiques'] = "Statistiques sur les API/Boutiques";
$t['StatsCommandes'] = "Statistiques ventes en ligne";
$t['StatsDemandesContacts'] = "Statistiques sur les demandes de contact";
$t['StatsEmailings'] = "Statistiques sur les campagnes d'emailing";
$t['StatsSondagesSatisfaction'] = "Statistiques sur la satisfaction clients";
$t['StatsURL'] = "Statistiques utilisation des Short Urls";
$t['Statut'] = "Statut";
$t['StructureFichiersCSV'] = "Structure des fichiers CSV :";
$t['Supprimer'] = "Supprimer";
$t['Surface'] = "Surface";
$t['Table'] = "Table";
$t['Taille'] = "Taille";
$t['TaillesPavillons'] = "Tailles des pavillons";
$t['TailleReelle'] = "Taille Réelle";
$t['TelechargerBatchs'] = "Télécharger des batchs";
$t['TemplateHTML'] = "Template HTML";
$t['Texte'] = "Texte";
$t['TexteAlternatif'] = "Texte alternatif";
$t['Themes'] = "Thèmes";
$t['ThemeBlog'] = "Thème de blog";
$t['ThemesBlog'] = "Thèmes de blog";
$t['ThemeParent'] = "Thème parent";
$t['TinyUrl'] = "Url raccourcie";
$t['Titre'] = "Titre";
$t['TitreURL'] = "Titre URL";
$t['Top5:'] = "Top 5 : ";
$t['TousBlogs'] = "Tous les blogs";
$t['Traductions'] = "Traductions";
$t['TraductionsCompletes'] = "Les traductions sont à jour.";
$t['TraductionsManquantes'] = "Les traductions manquantes pour le fichier";
$t['Tribune'] = "Tribune";
$t['TribuneImage'] = "TribuneImage";
$t['TxClics'] = "Taux de clics";
$t['TxDesabonnement'] = "Taux de désabonnés";
$t['TxNPAI'] = "Taux de NPAI";
$t['TxOuvertures'] = "Taux d'ouverture";
$t['TxReactivite'] = "Taux de réactivité";
$t['Type'] = "Type";
$t['TypeBatch'] = "Type de batch";
$t['TypeValeurs'] = "Type des valeurs";
$t['UniteMesure'] = "Unité de mesure";
$t['UniteVente'] = "Unité de vente";
$t['Uri'] = "URI";
$t['UrlKey'] = "Intitulé de l'URL";
$t['Utilisateur'] = "Utilisateur";
$t['UtilisateurCree'] = "L'utilisateur a été créé.";
$t['UtilisateurExiste'] = "Cet utilisateur existe déjà.";
$t['Utilisateurs'] = "Utilisateurs";
$t['UtilisateurSauvegarde'] = "Les données de cet utilisateur ont été sauvegardées.";
$t['UtilisateurSupprime'] = "L'utilisateur a été supprimé.";
$t['Utilisateurs'] = "Utilisateurs";
$t['Valeurs'] = "Valeurs";
$t['Validation'] = "Validation";
$t['Validation:'] = "Validation";
$t['VidePasDeChangements'] = "Laissez ce champs vide pour conserver l'ancienne valeur.";
$t['Vignette'] = "Vignette";
$t['Visibilite'] = "Visibilité";
$t['VoirListe'] = "Voir la liste";
$t['VoirListeStatistiquesEmailing'] = "Voir la liste des campagnes d'emailing";
$t['VoirListeUtilisateurs'] = "Voir la liste des utilisateurs";
$t['VoirSchemaHTML'] = "Voir le schéma en XHTML";
$t['VoirSchemaXML'] = "Voir le schéma en XML";
$t['VoirStatsEmailing'] = "Voir les statistiques concernant les emailings";
$t['VosCommentaires'] = "Vos commentaires";
$t['VosDonneesSauvegardees'] = "Vos données ont été sauvegardées.";
$t['VotreBillet:'] = "Votre billet";
$t['VotreFichierNonCSV'] = "Votre fichier n'est pas un document *.CSV.";
$t['VotreLogin'] = "Votre login :";
$t['VotreMotDePasse'] = "Votre mot de passe :";
$t['VousDevezRenseignerDate'] = "Vous devez indiquer une date.";
$t['VousDevezRenseignerTitre'] = "Vous devez indiquer un titre.";
$t['VousPasAutoriseVoirElement'] = "Vous ne disposez pas des droits pour accéder à cette page du site.";
$t['ZoneVents'] = "Zones des vents";

$t['DemoCKEditor'] = "Demo CKEditor";

$d['pages'] = array(
	'login' => "connexion",
	'accueil' => "accueil",
	'userlist' => "utilisateurs",
	'boutiques' => "shops",
	'batch' => "batch",
	'blog' => "blog",
	'useredit' => "utilisateurs",
	'moncompte' => "mon-compte",
	'notfound' => "page-introuvable",
	'forbidden' => "acces-interdit",
	'statsemailingedit' => "stats-emailing-edit",
	'statsemailinglist' => "stats-emailing-list",
	'statsmessageslist' => "stats-messages",
	'statssatisfaction' => "stats-satisfaction",
	'statsvisitesproduits' => "stats-vistes-produits",
	'reportingsatisfaction' => "reporting-satisfaction",
	'graphstats' => "graphs",
	'database' => "base-de-donnee",
	'contenu' => "contenu",
	'produits' => "produits",
	'fiches' => "fiches",
	'ficheperso' => "fiche-perso",
	'fichetechnique' => "fiche-technique",
	'ficheelement' => "fiche-technique-element",
	'fichematiere' => "fiche-matiere",
	'apiusers' => "utilisateurs-api",
	'apiroles' => "roles-api",
	'ckeditordemo' => "ckeditor-demo",
	'filterdemo' => "filter-demo",
	'dteditordemo' => "dteditor-demo",
	'dteditor' => "dteditor.js",
	'dteditorimage' => "dteditor-upload-image",
	'schemadb' => "schema-db",
	'trad' => "translations",
	'tribune' => "tribune",
	'tribuneimage' => "tribune-image",
	'tribuneimagecote' => "tribune-image-cote",
	'tribuneimagecotereplie' => "tribune-image-cote-replie",
	'htmleditor' => "htmleditor.js",
	'catalogueapidemo' => "catalogue-api-demo",
	'dashboard' => "dashboard",
	'cleansku' => "clean-sku",
	'cleandb' => "clean-db",
	'tools' => "outils",
	'filtreemails' => "filtre_emails",
	'calculvent' => "calcul-vent",
	'calculflags' => "calcul-event-flags",
	'statsapi' => "stats-api",
	'exportproduits' => "export-produits",
	'comparatif' => "comparatif",
	"blocs" => "blocs",
	"pages" => "Pages",
	"services" => "Services",
	"customers" => "Clients",
	"diaporamas" => "diaporamas",
	"menus" => "menus",
	"update" => "mise-a-jour",
    "statsshorturl" => "stats-short-url",
    "statscommandes" => "stats-commandes",
	"commandes" => "commandes",
	"impressioncommande" => "impression-commande",
	"gammes" => "gammes",
	"factures" => "factures",
	"aide" => "aide",
	"degressifs" => "degressifs",
	"assets" => "assets",
);

$d['hd_extensions'] = array(
	'' => "...",
	'jpg' => "JPEG",
	'tif' => "TIFF",
	'psd' => "Photoshop",
	'eps' => "EPS",
	'ai' => "Adobe Illustrator",
);
