<?php

$t['Accueil'] = "Home";
$t['Acces'] = "Access";
$t['Actions'] = "Actions";
$t['Accessoires'] = "Accessories";
$t['Active'] = "On";
$t['AdresseIP'] = "IP Address";
$t['Affichage'] = "Display";
$t['Affichage:'] = "Display";
$t['Aide'] = "Help";
$t['Ajouter'] = "Add";
$t['AjouterUneCampagneEmailing'] = "Add an emailing campaign";
$t['AjouterUnRole'] = "Add a rule";
$t['AjouterPrixDegressif'] = "Add a low price";
$t['AjouterRoleApi'] = "Add an API rule";
$t['AjouterUnAttribut'] = "Add an attribute";
$t['AjouterUnDocument'] = "Add a document";
$t['AjouterUneImage'] = "Add an image";
$t['AjouterUneOption'] = "Add an option";
$t['AjouterUneRegle'] = "Add a rule";
$t['AjouterUnUtilisateur'] = "Add a user";
$t['AjouterUnUtilisateurApi'] = "Add an API user";
$t['Annee'] = "Year"; 
$t['Annuler'] = "Cancel"; 
$t['Apercu'] = "View";
$t['Application'] = "Application";
$t['Applications'] = "Applications";
$t['Approved'] = "Approuved";
$t['AttenteTelechargement'] = "Téléchargement en cours...";
$t['AttentionNonSauvergarde'] = "Be careful : This item is not recorded.";
$t['AttentionSuppressionImage'] = "Be careful : adding and deleting an image are done without a backup.";
$t['Attributs'] = "Attributes";
$t['AttributsManagement'] = "Attributs management";
$t['Auteur'] = "Author";
$t['AvantagesProduit'] = "The + product";
$t['Barre'] = "Striked";
$t['BaseDeDonnees'] = "Database";
$t['Bienvenue'] = "Welcome";
$t['BilletBlog'] = "Blog Post";
$t['BilletdeBlog'] = "Blog post";
$t['BilletsduBlog'] = "Blog posts";
$t['Blog'] = "Blog";
$t['Categories'] = "Categories";
$t['Caracteristiques'] = "Caracteristics";
$t['CategorieParent'] = "Parent category";
$t['CeMois:'] = "Analytics for the current month.";
$t['Champs'] = "Fields";
$t['ChampIntitule'] = "Label field";
$t['ChampValeur'] = "Value field";
$t['Charger'] = "Load";
$t['ChoisissezTypeContenu'] = "Choose a content type.";
$t['Changer'] = "Change";
$t['ChoisissezProduit'] = "Choose your type of product.";
$t['Classement'] = "Range";
$t['Comparatif'] = "Comparison";
$t['Comparer'] = "Compare";
$t['Composition'] = "Composition";
$t['Conditionnement'] = "Packaging";
$t['Confirmer'] = "Confirm";
$t['Contenu'] = "Content";
$t['Couleur'] = "Color";
$t['Couleurs'] = "Colors";
$t['CochezApplications'] = "Check the applications  :";
$t['CochezAttributs'] = "Check the attributes :";
$t['Colisage'] = "Packing";
$t['Commentaires'] = "Commentes";
$t['CommentairesDeBlog'] = "Blog comments";
$t['CommentairesDesBlogs'] = "Blogs comments";
$t['CommentairesDesProduits'] = "Products comments";
$t['CommentairesDuBillet'] = "Post comments";
$t['CommentairesDuBlog'] = "Blog comments";
$t['CommentairesDuProduit'] = "Products comments";
$t['Composants'] = "Components";
$t['CorrespondanceMagento'] = "Magento correspondance";
$t['ConfirmerSuppression'] = "Are you sure ?";
$t['ConseilsEntretien'] = "Cleaning advices";
$t['Creer'] = "Create";
$t['CreerUtilisateur'] = "Create a new user";
$t['CreerBillet'] = "Create a blog post";
$t['CreerBlog'] = "Créer un blog";
$t['CreerNouveauCatalogue'] = "Create a new catalogue";
$t['CreerNouveauCommentaireBlog'] = "Create a new comment for a blog post";
$t['CreerNouveauCommentaireProduit'] = "Create a new comment for the product";
$t['CreerNouveauProduit'] = "Create a new product";
$t['CreerNouveauSku'] = "Create a new SKU";
$t['CreerNouvelleApplication'] = "Create a new application";
$t['CreerNouvelleGamme'] = "Create a new range";
$t['CreerNouvelleMatiere'] = "Create a new material";
$t['CreerNouvelAttribut'] = "Create a new attribute";
$t['CreerThemeBlog'] = "Create a new blog category";
$t['Dashboard'] = "Dashboard";
$t['Date'] = "Date";
$t['DateCreation'] = "Creation date";
$t['DateDebutVente'] = "Sale date from";
$t['DateFinVente'] = "Sale date to";
$t['DateAffichage'] = "Display date";
$t['DateEnvoi'] = "Register date";
$t['DemandesCatalogue'] = "Catalogue requests";
$t['DemandesDevis'] = "quote requests";
$t['DemandesInfo'] = "information requests";
$t['Declinaisons'] = "Variations";
$t['Desactive'] = "Off";
$t['Description'] = "Description";
$t['DescriptionCourte'] = "Short description";
$t['DesignationCommerciale'] = "Business name";
$t['Dessiner'] = "Draw";
$t['Diaporama'] = "Slideshow";
$t['Dimensions'] = "Sizes";
$t['Disapproved'] = "Disapproved";
$t['Document'] = "Document";
$t['DocumentFichier'] = "Document file";
$t['DocumentVignette'] = "Document thumbnail";
$t['Domaine'] = "Domain";
$t['DonneesAjoutees'] = "Datas have been recorded.";
$t['DonneesExistent'] = "These datas exist yet.";
$t['DonneesUpdated'] = "Datas have been updated.";
$t['Dupliquer'] = "Duplicate";
$t['EchantillonDisponible'] = "Sample available";
$t['EcoLabel'] = "Eco label";
$t['EditerCampagneEmailing'] = "Edit an emailing campaign";
$t['EditerBillet'] = "Edit blog post";
$t['EditerApplication'] = "Edit an application";
$t['EditerAttribut'] = "Edit an attribute";
$t['EditerCatalogue'] = "Edit a catalogue";
$t['EditerCategorie'] = "Edit a category";
$t['EditerBlog'] = "Edit a blog";
$t['EditerRegles'] = "Edit rules";
$t['EditerMatiere'] = "Edit a material";
$t['EditerProduit'] = "Edit a product";
$t['EditerSku'] = "Edit a SKU";
$t['EditerGamme'] = "Edit a range";
$t['EditerThemeBlog'] = "Edit the blog theme";
$t['EditerUtilisateur'] = "Edit an user";
$t['EditionCommentaire'] = "Edit the comment";
$t['Email'] = "E-mail";
$t['Emails'] = "E-mails";
$t['Emailings'] = "E-mailings";
$t['Emphase'] = "Emphasis";
$t['Enregistrer'] = "Save";
$t['EnregistrementAjoute'] = "Record added.";
$t['EnregistrementSauvegarde'] = "Record saved.";
$t['EnregistrementSupprime'] = "Record deleted.";
$t['Entrer'] = "Enter";
$t['Envoyer'] = "Send";
$t['Evidence'] = "Strong";
$t['ExpressionsTraduire'] = "translated sentences";
$t['FamillesMatieres'] = "Materials families";
$t['FamilleVente'] = "Business category";
$t['Fermer'] = "Close";
$t['Fiche'] = "Sheet";
$t['FicheMatiere'] = "Material sheet";
$t['FichesMatieres'] = "Material sheets";
$t['FicheTechnique'] = "Technical sheet";
$t['FichesTechniques'] = "Technical sheets";
$t['FicheTechniqueProduit'] = "Technical sheet";
$t['Filiale'] = "Subsidiary";
$t['FilialeConcernee'] = "Concerned subsidiary";
$t['FiliereRecyclage'] = "Recycling Paths";
$t['FiltreReset'] = "Reset filter";
$t['FiltreSearch'] = "Search";
$t['Images'] = "Images";
$t['ImpossibleAjoutPrixNul'] = "It's impossible to add a lower price to this product.";
$t['Informations'] = "Information";
$t['Gamme'] = "Range";
$t['GammeEssentiel'] = "Essential";
$t['GammeExpert'] = "Expert";
$t['GammePro'] = "Pro";
$t['GestionUtilisateurs'] = "Manage users";
$t['GestionBDD'] = "Manage Database";
$t['GestionBillets'] = "Manage blog posts";
$t['GestionContenu'] = "Manage content";
$t['ImageEmailing'] = "E-mailing screen capture";
$t['IntroAdmin'] = "Welcome on Doublet.pro, the Doublet products database.";
$t['GraphiqueTauxOuverture'] = "Openings rate graph";
$t['GraphiqueTauxReactivite'] = "Reactivity rate graph";
$t['GraphiqueTauxClics'] = "Clicks rate graph";
$t['GroupesUsers'] = "Profils";
$t['Image'] = "Image";
$t['Key'] = "Key";
$t['KPI'] = "Key indicators";
$t['Largeur'] = "Width";
$t['LesImages'] = "Images";
$t['Langue'] = "Language";
$t['Libelle'] = "Name";
$t['Lien'] = "Link";
$t['Liste'] = "List";
$t['ListeOfAccessoiresProduit'] = "Product accessories list";
$t['ListeOfApplications'] = "Applications list";
$t['ListeOfAttributs'] = "Attributes list";
$t['ListeOfBlogs'] = "Blogs list";
$t['ListeOfCatalogues'] = "Catalogues list";
$t['ListeOfComposantsProduit'] = "Components list";
$t['ListeOfDeclinaisonsProduit'] = "Variations list";
$t['ListeOfCommentaires'] = "Comments list";
$t['ListeOfGammes'] = "Ranges List";
$t['ListeOfMatieres'] = "Materials list";
$t['ListeOfProduits'] = "Product list";
$t['ListeOfProduitsCategories'] = "Products list for the category";
$t['ListeOfProduitsComplementaires'] = "Related products list";
$t['ListeOfProduitsSimilaires'] = "Similar products list";
$t['ListeOfRoles'] = "API roles list";
$t['ListeOfSku'] = "SKU list";
$t['ListeOfTables'] = "Tables list";
$t['ListeUtilisateurs'] = "Users list";
$t['ListeUtilisateursApi'] = "API users list";
$t['Longueur'] = "Length";
$t['Login'] = "Login";
$t['MarquesFournisseurs'] = "Manufacturers names";
$t['Matiere'] = "Material";
$t['Matieres'] = "Materials";
$t['Messages'] = "Messages/Quotes";
$t['Methode'] = "Methode";
$t['Methodes'] = "Methodes";
$t['MetaDescription'] = "Meta Description";
$t['MetaKeywords'] = "Meta Keywords";
$t['MetaTitle'] = "Meta Title";
$t['ModeEmploi'] = "Instructions";
$t['Montages'] = "Assembly";
$t['ModifierMonCompte'] = "Update my account";
$t['ModifierUtilisateur'] = "Update this user";
$t['MoisAout'] = "August";
$t['MoisAvril'] = "April";
$t['MoisDecembre'] = "December";
$t['MoisFevrier'] = "February";
$t['MoisJanvier'] = "January";
$t['MoisJuillet'] = "July";
$t['MoisJuin'] = "June";
$t['MoisMai'] = "May";
$t['MoisMars'] = "March";
$t['MoisNovembre'] = "November";
$t['MoisOctobre'] = "October";
$t['MoisSeptembre'] = "September";
$t['MonCompte'] = "My account";
$t['MoyenneClics'] = "Clicks rate";
$t['MoyenneNPAI'] = "No delivery rate";
$t['MoyenneOuverture'] = "Openings rate";
$t['MoyenneReactivite'] = "Reactivity rate";
$t['NbreCataloguesMois'] = "Quantity of catalogues per month";
$t['NbreContactsMois'] = "Quantity of messages per month";
$t['NbreDevisMois'] = "Quantity of quotes per month";
$t['NbreEmailDansDB'] = "Quantity of e-mail addresses in your listing";
$t['NbreEmailEnvoyes'] = "Quantity of sended e-mails";
$t['NbreEmailOuvert'] = "Quantity of opened e-mails";
$t['NbreEmailCliques'] = "Quantity of clicked e-mails";
$t['Nom'] = "Name";
$t['Norme'] = "Standard";
$t['NomCampage'] = "Campaign name";
$t['Nouveau'] = "New";
$t['NouveauCatalogue'] = "New catalogue";
$t['NouveauCommentaire'] = "New comment";
$t['NouveauDocument'] = "New document";
$t['NouveauProduit'] = "New product";
$t['NouveauRole'] = "New role";
$t['NouveauSku'] = "New SKU";
$t['NouveauTheme'] = "New theme";
$t['NouvelAttribut'] = "New attribute";
$t['NouvelUtilisateur'] = "New user";
$t['NouvelleApplication'] = "New application";
$t['NouvelleCategorie'] = "New category";
$t['NouvelleGamme'] = "New range";
$t['NouvelleMatiere'] = "New material";
$t['obligatoire'] = "required";
$t['Ou'] = "Or";
$t['OubliPassword'] = "forgotten password ?";
$t['Offline'] = "Offline";
$t['Offre'] = "Offer";
$t['Online'] = "Online";
$t['Option'] = "Option";
$t['Options'] = "Options";
$t['Ordre'] = "Rating";
$t['OrganisationsInter'] = "International Organisations";
$t['ParametresUtilisateur'] = "User settings";
$t['Parent'] = "Parent";
$t['PasAfficher'] = "Do not show";
$t['Pays'] = "Country";
$t['Parametres'] = "Settings";
$t['Password'] = "Password";
$t['ParPage'] = "per page";
$t['Personnalisation'] = "Personalization";
$t['PictosVente'] = "Sales icons";
$t['Poids'] = "Weight";
$t['Presentation'] = "Presentation";
$t['Prix'] = "Price";
$t['PrixDegressifs'] = "Lower prices";
$t['PrixFranco'] = "Shipping costs applied.";
$t['PrixHT'] = "Price without taxes";
$t['PrixUnitaire'] = "Unit Price";
$t['Produits'] = "Products";
$t['ProduitsComplementaires'] = "Related products";
$t['ProduitsSimilaires'] = "Similar products";
$t['Profondeur'] = "Deepth";
$t['Public'] = "Public";
$t['QrCode'] = "QrCode";
$t['Quantite'] = "Quantity";
$t['RechercheAvancee'] = "Advanced search";
$t['Reduction'] = "Discount";
$t['ReductionPourcentage'] = "% discount";
$t['Referencement:'] = "SEO";
$t['Reference'] = "Reference";
$t['Referencement'] = "SEO";
$t['RefRAL'] = "RAL";
$t['RefUltralog'] = "Ultralog ref";
$t['Regions'] = "States";
$t['ReglesRole'] = "Role rules";
$t['ReglesUtilisateur'] = "User rules";
$t['RepartitionEmailingsPays'] = "Distribution of e-mailings by countries";
$t['Reinitialiser'] = "Reset";
$t['Retour'] = "Back";
$t['RetourCatalogue'] = "Back to catalogue";
$t['RetourBlog'] = "Back to blog";
$t['RetourListeStats'] = "Back to the analytics";
$t['Role'] = "Role";
$t['Roles'] = "Roles";
$t['RolesAPI'] = "API roles";
$t['Sauvegarder'] = "Save";
$t['SchemaDB'] = "Architecture";
$t['SelectFichier'] = "Select a file : ";
$t['Spam'] = "Spam";
$t['Statut'] = "Statut";
$t['SelectAnnee'] = "Select a year : ";
$t['SelectFiliale'] = "Select a subsidiary : ";
$t['Selectionnes'] = "Selected";
$t['SelectionnezTable'] = "Select one table in the list.";
$t['SelectionnezBillet'] = "Select a blog post";
$t['SesDimensions'] = "Dimensions";
$t['SesDroits'] = "Rules";
$t['SesResultats'] = "Results";
$t['SonIdentite'] = "Identity";
$t['Souligne'] = "Underscored";
$t['Statistiques'] = "Analytics";
$t['StatsDemandesContacts'] = "Messages analytics";
$t['StatsEmailings'] = "E-mailing analytics";
$t['Supprimer'] = "Delete";
$t['Table'] = "Table";
$t['Taille'] = "Size";
$t['TailleReelle'] = "Real size";
$t['Texte'] = "Text";
$t['TexteAlternatif'] = "Alt text";
$t['Themes'] = "Themes";
$t['ThemeBlog'] = "Blog theme";
$t['ThemesBlog'] = "Blog themes";
$t['ThemeParent'] = "Parent theme";
$t['TinyUrl'] = "Tiny Url";
$t['Titre'] = "Title";
$t['TitreURL'] = "URL title";
$t['Outils'] = "Tools";
$t['Top5:'] = "Top 5 : ";
$t['TousBlogs'] = "All the blogs";
$t['Traductions'] = "Translations";
$t['TraductionsCompletes'] = "Translations updated.";
$t['TraductionsManquantes'] = "Missing translations for the file";
$t['Tribune'] = "Tribune";
$t['TribuneImage'] = "TribuneImage";
$t['TxClics'] = "Clicks rate";
$t['TxNPAI'] = "No delivery rate";
$t['TxOuvertures'] = "Openings rate";
$t['TxReactivite'] = "Reactivity rate";
$t['Type'] = "Type";
$t['TypeDocuments'] = "Type of documents";
$t['TypeValeurs'] = "Type of values";
$t['UniteMesure'] = "Measure Unit";
$t['UniteVente'] = "Sale Unit";
$t['Uri'] = "URI";
$t['UrlKey'] = "Url key";
$t['Utilisateur'] = "User";
$t['UtilisateursAPI'] = "API users";
$t['UtilisateurCree'] = "The user has been created.";
$t['UtilisateurExiste'] = "This user already exists.";
$t['UtilisateurSauvegarde'] = "The data for this user have been saved.";
$t['UtilisateurSupprime'] = "The user has been deleted.";
$t['Utilisateurs'] = "Users";
$t['Valeurs'] = "Values";
$t['Validation'] = "Confirm";
$t['Validation:'] = "Confirm :";
$t['VidePasDeChangements'] = "Let empty for no change.";
$t['Vignette'] = "Thumbnail";
$t['Visibilite'] = "Visibility";
$t['VoirListe'] = "See the list";
$t['VoirListeStatistiquesEmailing'] = "E-mailings campaigns list";
$t['VoirListeUtilisateurs'] = "Users list";
$t['VoirSchemaHTML'] = "See the database architecture in HTML";
$t['VoirSchemaXML'] = "See the database architecture in XML";
$t['VoirStatsEmailing'] = "See the e-mailings analytics";
$t['VosCommentaires'] = "Yours comments";
$t['VotreBillet:'] = "Your post";
$t['VotreLogin'] = "Your login :";
$t['VotreMotDePasse'] = "Your password :";
$t['VousDevezRenseignerDate'] = "You must indicate a date.";
$t['VousDevezRenseignerTitre'] = "You must indicate a title.";
$t['VousPasAutoriseVoirElement'] = "You are not allowed to see this page.";
$t['VosDonneesSauvegardees'] = "Your data have been saved.";

$t['DemoCKEditor'] = "CKEditor's demo";

$d['pages'] = array(
	'login' => "login",
	'accueil' => "home",
	'userlist' => "users",
	'batch' => "batch",
	'blog' => "blog",
	'useredit' => "users",
	'moncompte' => "my-account",
	'notfound' => "no-found",
	'forbidden' => "acces-interdit",
	'statsemailingedit' => "stats-emailing",
	'statsemailinglist' => "stats-emailing",
	'statsmessageslist' => "stats-messages",
	'statssatisfaction' => "stats-satisfaction",
	'statsvisitesproduits' => "stats-products-views",
	'reportingsatisfaction' => "reporting-satisfaction",
	'graphstats' => "graphs",
	'database' => "database",
	'contenu' => "content",
	'produits' => "products",
	'fiches' => "factsheets",
	'fichetechnique' => "factsheet",
	'ficheperso' => "personal-factsheet",
	'ficheelement' => "factsheet-element",
	'fichematiere' => "material-sheet",
	'apiusers' => "api-users",
	'apiroles' => "api-roles",
	'ckeditordemo' => "ckeditor-demo",
	'filterdemo' => "filter-demo",
	'dteditordemo' => "dteditor-demo",
	'dteditor' => "dteditor.js",
	'dteditorimage' => "dteditor-upload-image",
	'schemadb' => "schema-db",
	'trad' => "translations",
	'tribune' => "tribune",
	'tribuneimage' => "tribune-image",
	'tribuneimagecote' => "tribune-image-cote",
	'tribuneimagecotereplie' => "tribune-image-cote-replie",
	'htmleditor' => "htmleditor.js",
	'catalogueapidemo' => "catalog-api-demo",
	'dashboard' => "dashboard",
	'cleansku' => "clean-sku",
	'cleandb' => "clean-db",
	'tools' => "outils",
	'filtreemails' => "filter_email",
	'calculvent' => "calcul-vent",
	'calculflags' => "calcul-event-flags",
	'statsapi' => "stats-api",
	'exportproduits' => "export-products",
	'comparatif' => "comparison",
	"blocs" => "blocks",
	"pages" => "Pages",
	'services' => "Services",
	'customers' => "Customers",
	"diaporamas" => "slideshows",
	"menus" => "menus",
	"update" => "update",
    "statsshorturl" => "stats-short-url",
    "statscommandes" => "stats-orders",
	"commandes" => "commandes",
	"gammes" => "ranges",
	"factures" => "invoices",
	"aide" => "help",
);

$d['hd_extensions'] = array(
	'' => "...",
	'jpg' => "JPEG",
	'tif' => "TIFF",
	'psd' => "Photoshop",
	'eps' => "EPS",
	'ai' => "Adobe Illustrator",
);
